name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Git repository
        uses: actions/checkout@v2  
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          args: "-g -pdf -file-line-error -halt-on-error -interaction=nonstopmode"
          working_directory: src/
          root_file: main.tex
            
      - name: Upload to Netlify     
        uses: MrFlynn/upload-to-netlify-action@v2
        with:
          source-file: "src/main.pdf"
          destination-path: "/seminar.pdf"
          site-name: mip-star-equals-re-seminar
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
